# Generated by Django 5.2.3 on 2025-07-06 10:11

import datetime
import django.db.models.deletion
import phonenumber_field.modelfields
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300, verbose_name='Username')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=50, verbose_name='Отчества')),
                ('birthday', models.DateField(blank=True, default=None, null=True, verbose_name='День рождение')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Контактный номер телефона', max_length=128, region=None, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=70, unique=True, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=profiles.models.make_upload_path, verbose_name='Аватарка')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Registration date')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['surname', 'name', 'middlename'],
            },
        ),
    ]
